version: '3.8'

services:
  redis:
    image: redis:7.0.11-alpine

  postgres:
    container_name: db
    image: postgres:16.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

  django:
    container_name: django
    build:
      context: .
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    env_file: .env
    volumes: 
      - .:/usr/src/app/
    ports:
      - 8001:8000
    depends_on:
      - redis
      - postgres

  celery:
    container_name: celery
    build:
      context: .
    command: celery --app=IphoneUtils worker -l INFO
    volumes: 
      - .:/usr/src/app/
    depends_on:
      - redis
      - postgres

volumes:
  postgres_data: